### ISSUE TITLE
Add show/hide image option

### ISSUE THREAD

**Issue by nothize** [Strav/Change-Colors#1]
Hello, have you plan to add this?

I've just added it bcoz I need it to have a complete plugin..

I'm willing to submit a patch, just let me know.

**Comment by Strav** [comment]
Yep I thought about it (but was kinda afraid to bloat the options page, thinking people might as well use elinks, lynx and such) and upon reconsideration though, I feel it's a good idea. I'll add your patch (perhaps with some modifications to make sure it fits the whole), but I'll publish it as soon as I've corrected the annoyance one person mentionned in google's extensions gallery: upon updating, the default settings are overwriting the user's. If I correctly understand github, I think you can just fork my project, apply your modifications and then I'll merge your changes (perhaps overkill for a few lines of code you might tell me, but I only wish to experiment with it ;)

**Comment by Strav** [comment]
Correction, I did some tests and those tests as well as the original poster for the update issue concluded that it's a non-issue, so well... I'll update the extension itself as soon as I'll have merged your additions. Many thanks for that btw.

**Comment by nothize** [comment]
Ok done forking and committed the changes.

**Comment by Strav** [comment]
He. I just commited your changes but I would appreciate if you'd test your modifications before submitting them. 

The css code injection couldn't worked the way you wrote it, you also forgot to set a default value for that option when the users will first install the extension (see setDefaults in background_page) and you introduced a bug by removing the function calls in checkRadio (they were used to trigger the showing and hiding of the colors and fonts options upon loading the options page). You can check the details on my last commit.

Besides, I tried to fetch your modifications from your git repository and I couldn't get to your last commit. There must have been some error somewhere (perhaps on my part), but you can try to: git clone git://your_git_repo's_address in a temp folder to see if you can get to your last commit... I couldn't.

Again, your contributions will always be welcomed, just take a little while to review your changes before. ; )

**Comment by nothize** [comment]
Could you point out in which way it failed to work because I have tested it locally.... I made the change initially through local modification of the extension, then do a diff against your version and finally a patch to my forked version.

In fact I have missed one additional change I later added:
html > body \* { background-image: none !important;}
some website uses the background-image inside an anchor that survived until I explicitly adding this CSS together with the no ShowImage option. Perhaps you intentionally let them survive because they are clickable?

Oh yes I have missed the setDefaults() because I thought the default would belongs to JSON.parse(..)'s return value when the option doesn't exist(though I haven't verified it)..it is how I interpret default values. :)

I intentionally removed the function calls of defFunction() and overrideFunction() since I think they are replicating the onClick handler of the corresponding element. In fact their actions are identical so why should we introduce more parameters to radioCheck? The partial modification is to demonstrate the same functionality of using the onClick() instead of the defFunction() for my own testing purpose.

Sorry it's my first time to use github......I forked your project several times and even committed with a name "unknown"...so I removed it and redo ....until I finally worked it out. But github seems to experience some kind of problem, either the "deleted" repos is "cached" or github unable to reflect the latest information in some places.

5eb7884b512e8fd925c3cb578db696d69c073abb was the commit I made finally with my nick on it....

I just tried to git clone the http://github.com/nothize/Change-Colors.git but failed with refs not found.

git://github.com/nothize/Change-Colors.git is okay and the latest commit is there.

Perhaps this change is too rush and I didn't really expect it will be contributed back as it is not often the case else where. :)

Thanks for your adoption so that I can enjoy upgrading your extension without suffering from my personal need.

I see that it is possible to leave comment in my own code thru github's web interface. Is it possible to open it for others bcoz I can't comment on your commits. I think it would be easier for you to just review and comment my changes first and let me correct them before your final merge.

**Comment by Strav** [comment]
He. 

For my test I just went to a random site to see if the images were indeed removed and they remained. In the injectCss string you added something like img{display: hidden; } while html > body img { display:none !important; } was needed.

As for the default values, json.parse will crash if given an undefined object so you have to test if localStorage['something'] exists and if not, set a default value according to the config you wish. I just changed the mechanism I previously used though for this was the reason some previous updates were broken. Namely, I kept a key/value named: isFirstStart, intended to force the setting of default values when a user first installed the extension. Then I accumulated the new options there but users only updating were prevented to get the proper default value for the new option since they already had this isFirstStart key set to true in their localStorage.

Finally, concerning the defFunction(), I didn't thought that onClick could be called this way and yep, that's nicer than the way I did it. (btw I just commited that change)

I'll have to test that when I'll have a moment.

Be certain I'll check your branch for any additions you might come up with, it's very appreciate that you take some time to contribute.

**Comment by nothize** [comment]
Ahha, I see what you mean now!

I see..

Since the restoreOptions() is run after the options.html is loaded, those onClick functions should be already available. As I didn't experience any problem in my local version, I'm not sure why you say they cannot be replaced by explicitly calling to the onClick() of the elements.

I will find a way to merge your latest changes before I make any changes to minimize the potential conflicts.

**Comment by Strav** [comment]
I edited my post above... turns out you were right. :)
