### ISSUE TITLE
Scrollbar color

### ISSUE THREAD

**Issue by u1ik** [Strav/Change-Colors#2]
It would be nice to add an option to control the color of the scrollbar. When I am reading a big text on black background, the bright scrollbar distracts me. I could change the scrollbar color by applying a dark theme, but it seems to be an overkill.

My quick and dirty solution for now is to add these lines to buildCssToInject:
    css += '::-webkit-scrollbar{background: black ;}'
    css += '::-webkit-scrollbar-thumb{background : someothercolor;}'

**Comment by Strav** [comment]
That could be a nice addition, though, as always, I'm worried about bloating the options page. I'll think about it. (and thanks for the idea btw).

**Comment by Strav** [comment]
He. I gave a try in implementing the scrollbar style override and I'm now wondering if it shouldn't be a theme concern. I've seen that webkit offers plenty of way to customize the scrollbars but to get something that looks decent in most of circumstances is another story... I'll still dig a little on the subject.

**Comment by gladstone** [comment]
This is a job for a theme, not an extension. "Use a Chrome Theme for some control of the color scheme of the Chrome user interface." from: [Chromium accessibility](http://sites.google.com/a/chromium.org/dev/developers/design-documents/accessibility#TOC-High-Contrast-Support)
