### ISSUE TITLE
Add not apply override this domain option

### ISSUE THREAD

**Issue by dtakura** [Strav/Change-Colors#3]
When check "All override on all pages" option, I think "Not apply override this domain" option is very useful.

As web page is usually bright for me, I check "All override on all pages". However, there are some pages with a good design. When view such pages, I use short cut key "Ctrl + Shift + G" now. If  there is "Not apply override this domain" option in this extension, it is more cool!

**Comment by Strav** [comment]
Agreed. I'll review the rules for overriding the page in favor of this option, then I'll see if everything is still as I like, then I'll upgrade the extension. Thanks for the suggestion!

**Comment by Strav** [comment]
Hi there. I just committed the modifications. Before I submit this update, do you mind testing it (see the branch Invert-controls)? I'll be waiting your comments. Thanks!

**Comment by dtakura** [comment]
Wow! Thank you for the modifications so quickly!

I hvae tested. When check "All override on all pages" and "No global override on this page" or "No global override on this domain" at some pages, it works pretty good! But when restart my google chrome, it override on the pages and domains that are applyed to "No global override". It seems not to save "No global override" options, because other options work correctly.

【Test method】
1)Download your extension from "http://github.com/Strav/Change-Colors/commit/28933d28dd9e64497777373b164572b0fa9a23c0".
2)Pack and install it from chrome.
3)Check "All override on all pages".
4)Check "No global override on this page" or "No global override on this domain" at some pages.
5)Restart Google Chrome.

【My enviroment】
Google Chrome 5.0.356.2 dev
Windows XP SP2

■Add:
Now I add some code to "background_page.html". The problem is not occur, and it works correctly.

function getOverrides(){
    OverridenDomains = JSON.parse(localStorage["OverridenDomains"]);
    OverridenPages = JSON.parse(localStorage["OverridenPages"]);
    NotOverridenDomains = JSON.parse(localStorage["NotOverridenDomains"]);
    NotOverridenPages = JSON.parse(localStorage["NotOverridenPages"]);
    IsOverrideAll = JSON.parse(localStorage["OverrideAll"]);
}

■Other problem(not fatal)
When check ON/OFF override options, it sometimes does not works correctly. If reload the page, it allways works correctly.

■Suggestion
I think it makes this extension more better that the domains and pages can be showed and edited from GUI. As I will directly edit localstorage, it is not problem for me.

■Etc
I can't speak english and my english skill is too poor. Please point it out if the mistake is found in my sentences.

**Comment by Strav** [comment]
He. 

Thanks for your test! I don't why the two lines in getOverrides were omitted in my commit, I must have removed them by error - I'm very grateful you caught this error. As for your other suggestion, I initially wanted to include something similar in the options page but I kinda lost my interest (the only use case I can think of would be if someone has so many override exceptions that this starts to make the extension slow). If you have another use case in mind, please tell me. Note, I'm not saying I won't include the option, only that I wish to be really careful not to clutter the options page. (chance are I will include it anyways ;)

As for your english, I really don't mind. If you must know, "Please point it out if the mistake is found in my sentences." Is properly written as: "Please point it out if you find any mistakes in my sentences."

**Comment by dtakura** [comment]
Thanks for your reply and advise for my english! I wholly agree with your mind. I have no idea about another case. I do not feel that your extension slowed when I override many pages. Generally, functionality is frequently difficult to coexist with brevity. But, I feel that your extension achieves that now!

**Comment by Strav** [comment]
He. I'm wondering if you wouldn't have a little spare time to test the latest version of my extension. I did quite extensive tests on my part but as I've refactored much of the code, I would really appreciate if someone can test on their actual data to ensure everything goes well. 

Thanks again for your previous comments!

**Comment by Strav** [comment]
(note: the latest branch is called: refactor)

**Comment by dtakura** [comment]
Hi. Thanks for your update! It is very nice that the icon changes according to the state. I have tested the latest version. Keyboard shortcuts is not available in the latest version, though it is available in version 2.12. There does not seem to be other bugs. Other functions work pretty good!

If you need someone to test your extension, I would assist as long as I have spare time.

[Enviroment]
The version of extension : http://github.com/Strav/Change-Colors/commit/16d02b850bed2d440012a5838cf4c0a46cf60ff1
Google Chrome 5.0.360.0 dev
Windows XP SP2
