### ISSUE TITLE
Get rid of white screen when loading pages.

### ISSUE THREAD

**Issue by seanturvey** [Strav/Change-Colors#4]
I use your extension to make pages as dark as possible.  I suffer from migraines which cause photophobia (increased sensitivity to light).  When loading a page which hasn't been loaded during the present session, there is a brief flash of white screen.  This causes a lot of pain.

Would it be possible to change the white to your selected background colour?

**Comment by Strav** [comment]
He there.

I've tried to address this problem before, made some progress but unfortunately, the current state of affairs is perhaps the best that's possible to achieve. The styling override is injected as a style node before the documentElement and this is as soon as I could get. I'll give it another try but chances are dim.

I'll keep you posted.

Thanks!

**Comment by gladstone** [comment]
I would assume extensions are parsed after opening a new tab (also maybe DOMContentLoaded?) and therefore it's impossible to set it via this method without the flash.

This would have to be set at the browser level (Firefox has it in _Preferences > Conent > (Fonts & colors) > Colors_), though I can't find a similar option in Chrome/WebKit.

p.s. "... but chances are _dim_" -- no pun intended eh!
