### ISSUE TITLE
Keep it simple

### ISSUE THREAD

**Issue by gladstone** [Strav/Change-Colors#5]
Although useful, I think the image and flash blockers bloat this extension. Stick to the [KISS Principle](http://en.wikipedia.org/wiki/KISS_principle): there are other extensions that provide this functionality.

**Comment by Strav** [comment]
I know that, this is mostly what I replied to the people asking for those changes (and for any feature for that matter). But then, it occurred to me that some people really might want the behavior of hiding/showing flash images to follow the extension's override defined for a page or a domain so I added the options. This is however the current limit of optional features I'm willing to put in the option's page, if any more are needed, I'm thinking about an advanced options section, where hide images/flash will be located.

Anyhow, thanks for you comment. I really do wish to keep simplicity in mind.
